# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #контейнер с Nginx
  nginx:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    # проброс портов
    ports:
      - "80:80"
    volumes:
       - ./app:/data/application.local
       - ./logs/nginx:/var/log/nginx
    networks:
      - app-network

  #Контейнер с PHP-FPM, назовём его app
  app:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./config/fpm
      dockerfile: Dockerfile
    image: myapp/php # имя будущего образа
    environment:
      REDIS_HOST: memcached
      MEMCACHED_HOST: redis
      MYSQL_HOST: mysql
    ports:
      - 9001:9001
    container_name: app # имя контейнера после запуска
    volumes:
       - ./app:/data/application.local
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

  mysql:
    restart: always
    build:
      context: ./config/mysql
      dockerfile: Dockerfile
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: otus
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    container_name: mysql
    networks:
      - app-network

  memcached:
    image: memcached
    container_name:  memcached
    networks:
      - app-network
    ports:
      - 11211:11211
  
  redis:
    image: redis
    container_name: redis
    networks:
      - app-network
    ports:
      - 6379:6379

#Docker Networks
networks:
  app-network:
    driver: bridge